[project]
name = "try-openai-agents-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dspy>=3.0.4",
    "openai-agents[litellm]>=0.6.1",
    "pydantic>=2.12.4",
    "typer>=0.20.0",
]
